name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: yarn install
      uses: Borales/actions-yarn@v2.3.0
      with:
        # Yarn command
        cmd: install
        
    - name: yarn build
      uses: Borales/actions-yarn@v2.3.0
      with:
        # Yarn command
        cmd: build
        
    - name: yarn test
      uses: Borales/actions-yarn@v2.3.0
      with:
        # Yarn command
        cmd: test

    - name: deploy
      uses: actions-hub/gcloud@300.0.0
      env:
        PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
        APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      with:
        args: app deploy app.yaml